[project]
name = "hotel-reservation"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-storage>=3.13.1",
    "imbalanced-learn>=0.14.2",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "mlflow>=2.10.0",
    "numpy>=2.4.6",
    "pandas<3",
    "protobuf<=6",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "setuptools<70.0.0",
    "xgboost>=3.2.0",
]
